### ISSUE TITLE
Random NPE in accessing getDevicesUrl Method.

### ISSUE THREAD

**Issue by sairajkishore** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#81]
Hi,

Am getting below random crash due to null pointer exception as below, could you let me know the reason for this? is there any fix available for this?

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.lang.AbstractStringBuilder.(AbstractStringBuilder.java)
       at java.lang.StringBuilder.(StringBuilder.java)
       at com.ibm.mobilefirstplatform.clientsdk.android.push.internal.MFPPushUrlBuilder.getDevicesUrl(Unknown Source)
       at com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPush.sendMessageDeliveryStatus(Unknown Source)
       at com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPushIntentService.setAppForeground(Unknown Source)

**Comment by AnanthaKrish** [comment]
@sairajkishore Let me look into this issue .... I will get back to you soon..

**Comment by AnanthaKrish** [comment]
@sairajkishore is this issue [80](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-android-push/issues/80 ) happening at the same time ?

**Comment by sairajkishore** [comment]
No both are different issues but randomly occurring.

**Comment by sairajkishore** [comment]
Hi ,is above mentioned issue is fixed? available?

**Comment by AnanthaKrish** [comment]
@sairajkishore I am not able to recreate this issue ... do you have anymore logs ?

**Comment by sairajkishore** [comment]
Hi,
below are the logs i found this may be useful.

**UnRegister logs**
 Error unregistering with bluemix:com.ibm.mobilefirstplatform.clientsdk.android.push.api.a: , Message : {"code":"FPWSE0001E","message":"Not Found - The target resource 'PushDevice' does not exist. Check the 'ee335bad-a042-3f93-8b6c-5010b444870c' parameter."}, statusCode : 404

Error unregistering with bluemix:com.ibm.mobilefirstplatform.clientsdk.android.push.api.a: , Message : java.net.UnknownHostException: Unable to resolve host "imfpush.ng.bluemix.net": No address associated with hostname, statusCode : 0

Error unregistering with bluemix:com.ibm.mobilefirstplatform.clientsdk.android.push.api.a: , Message : java.net.SocketTimeoutException: timeout, statusCode : 0

**Comment by AnanthaKrish** [comment]
@sairajkishore  How you are adding the region ?

**Comment by sairajkishore** [comment]
This is how am adding the region.
 BMSClient.getInstance().initialize(mContext, BMSClient.REGION_US_SOUTH);

**Comment by AnanthaKrish** [comment]
I think its a network issue . @sairajkishore are you getting this error every time ?

**Comment by sairajkishore** [comment]
Not every time but for some user's.

**Comment by AnanthaKrish** [comment]
Its looks like the network issue .
