### ISSUE TITLE
Android O Push Notification

### ISSUE THREAD

**Issue by sairajkishore** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#88]
In android O am not able to get push notification.should we need to change notification builder?

**Comment by AnanthaKrish** [comment]
@sairajkishore It should work. I am using an Android O device for testing, it works. To get Android O based push notifications **features** we need to change the Notification Builder. We will release that soon.

**Comment by sairajkishore** [comment]
Also could you please update
1.Sample App for Android O support.
2.Also Library  for Android O support which includes FCM libraries.

**Comment by AnanthaKrish** [comment]
@sairajkishore We will do that during the new sdk release

**Comment by sairajkishore** [comment]
Any idea when it could be in and around? as i just want to plan for my next release?

**Comment by AnanthaKrish** [comment]
@sairajkishore Do you want the specific Android O features to be available in SDK ?

**Comment by sairajkishore** [comment]
As Notification Manager changes is  required to support Android O and Notification stuff is a part of SDK ,so we need updated SDK.

**Comment by AnanthaKrish** [comment]
If you want to try , please try to extend the `com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPushIntentService.java` file

**Comment by AnanthaKrish** [comment]
@sairajkishore Without any modification in the current code Android O devices will get notifications. But this will not have any android O features. 
Are you able to get notifications in Android O ?

**Comment by sairajkishore** [comment]
If the preconditions are 
Build  project with android O and target SDK is O, installed on android O device 
we are getting notification event but Notification manager does not show notification popup, in order to get this we need to set channel  for Notification manager in O also fire base library also should be updated if we refer O documentation.So modifications are required definitely.

**Comment by sairajkishore** [comment]
If the preconditions are
Build project with android O and target SDK is O, installed on android O device
we are getting notification event but Notification manager does not show notification popup, that is the existing issue am facing.Earlier build for target 7 on O devices notification used to come.

 in order to get this we need to set channel for Notification manager in O also fire base library also should be updated if we refer O documentation.So modifications are required definitely.

**Comment by AnanthaKrish** [comment]
@sairajkishore Yes I know that . I will let you know once its done.

**Comment by sairajkishore** [comment]
Also this is one of the crash log which i recently got.

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=6
       at com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPush.getInstance(Unknown Source)
       at com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPushIntentService.setAppForeground(Unknown Source)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
       at com.google.firebase.iid.zzc.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
